import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { activityTypes, calculateCO2, type ActivityType } from '../shared/emissions';
import { Activity, BarChart3, CalendarDays, ChevronDown, CircleHelp, CloudSun, Leaf, Menu, Plus, Settings, SlidersHorizontal, Target, Trash2, X } from 'lucide-react';
import './styles.css';
import './hero-action.css';

type Type = ActivityType;
type Entry = { id:string; type:Type; quantity:number; unit:string; factor:number; co2:number; date:string; note:string; unusual?:boolean };
const FACTORS: Record<Type,{factor:number;unit:string;icon:string;color:string}> = {
  Car:{factor:.2,unit:'km',icon:'🚗',color:'#ff8c5a'}, Bus:{factor:.08,unit:'km',icon:'🚌',color:'#e3ae49'}, Flight:{factor:.25,unit:'km',icon:'✈️',color:'#7798ef'}, Electricity:{factor:.8,unit:'kWh',icon:'⚡',color:'#a879e6'}, 'Vegetarian Meal':{factor:.5,unit:'meals',icon:'🥗',color:'#58b88b'}, 'Non-Vegetarian Meal':{factor:2,unit:'meals',icon:'🍗',color:'#df7185'}
};
const TYPES = activityTypes;
const key='planetpulse.activities.v1', targetKey='planetpulse.target.v1';
const fromApi=(e:any):Entry=>({id:e.id,type:e.type,quantity:e.quantity,unit:e.unit,factor:e.emissionFactor,co2:e.co2Kg,date:String(e.date).slice(0,10),note:e.note||'',unusual:e.unusual});
const fmt=(n:number)=>n.toLocaleString(undefined,{minimumFractionDigits:1,maximumFractionDigits:1});
const isoToday=()=>new Date().toISOString().slice(0,10);
function weekStart(d=new Date()){ const x=new Date(d); const day=(x.getDay()+6)%7; x.setHours(0,0,0,0); x.setDate(x.getDate()-day); return x }
function toIso(d:Date){ const z=new Date(d.getTime()-d.getTimezoneOffset()*60000); return z.toISOString().slice(0,10) }
function inWeek(date:string){ const start=toIso(weekStart()), end=new Date(weekStart()); end.setDate(end.getDate()+6); return date>=start&&date<=toIso(end) }
function calculate(type:Type,quantity:number){ const x=calculateCO2(type,quantity); return {factor:x.emissionFactor,unit:x.unit,co2:x.co2Kg} }
function seed():Entry[]{ const now=weekStart(); const dates=[0,1,2,3,4].map(i=>{const d=new Date(now);d.setDate(now.getDate()+i);return toIso(d)}); return [ ['Car',10,0,'Morning commute'],['Bus',15,1,'Office trip'],['Electricity',5,2,'Home usage'],['Vegetarian Meal',2,3,'Lunch'],['Non-Vegetarian Meal',1,4,'Dinner'] ].map(([type,quantity,i,note],idx)=>{const c=calculate(type as Type,quantity as number);return {id:'demo'+idx,type:type as Type,quantity:quantity as number,...c,date:dates[i as number],note:note as string}}) }

function App(){
 const [page,setPage]=useState('Dashboard'), [entries,setEntries]=useState<Entry[]>([]), [target,setTarget]=useState(50), [menu,setMenu]=useState(false), [showForm,setShowForm]=useState(false), [form,setForm]=useState({type:'Car' as Type,quantity:'',date:isoToday(),note:''}), [absurd,setAbsurd]=useState(false), [filters,setFilters]=useState({type:'All',range:'All time',sort:'Newest',from:'',to:''}), [del,setDel]=useState<string|null>(null), [toast,setToast]=useState(''), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{try{const [activities,settings]=await Promise.all([fetch('/api/activities'),fetch('/api/settings')]);if(!activities.ok||!settings.ok)throw new Error();setEntries((await activities.json()).map(fromApi));setTarget((await settings.json()).weeklyTarget)}catch{setToast('Could not connect to the local database. Start with npm run dev.')}finally{setLoading(false)}})()},[]);
 const weekly=useMemo(()=>entries.filter(e=>inWeek(e.date)),[entries]); const weekCO2=weekly.reduce((s,e)=>s+e.co2,0), total=entries.reduce((s,e)=>s+e.co2,0), remaining=target-weekCO2, progress=target?weekCO2/target*100:0;
 const cats=useMemo(()=>TYPES.map(t=>({type:t,value:entries.filter(e=>e.type===t).reduce((s,e)=>s+e.co2,0)})).filter(x=>x.value),[entries]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(weekStart());d.setDate(d.getDate()+i);const date=toIso(d);return {date,label:d.toLocaleDateString(undefined,{weekday:'short'}),value:weekly.filter(e=>e.date===date).reduce((s,e)=>s+e.co2,0),today:date===isoToday()}}),[weekly]);
 const add=async(override=false)=>{if(saving)return;const q=Number(form.quantity);if(!Number.isFinite(q)||q<=0||q>10000000||!form.date){setToast('Enter a valid quantity and date.');return} if(q>10000&&!override){setAbsurd(true);return}setSaving(true);try{const res=await fetch('/api/activities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:form.type,quantity:q,date:form.date,note:form.note,unusual:q>10000})});if(!res.ok)throw new Error();const entry=fromApi(await res.json());setEntries(es=>[entry,...es]);setShowForm(false);setAbsurd(false);setForm({type:'Car',quantity:'',date:isoToday(),note:''});setToast('Activity saved — your dashboard is updated.')}catch{setToast('Could not save activity. Please try again.')}finally{setSaving(false)}};
 const remove=async(id:string)=>{try{const res=await fetch(`/api/activities/${id}`,{method:'DELETE'});if(!res.ok)throw new Error();setEntries(es=>es.filter(e=>e.id!==id));setDel(null);setToast('Activity deleted.')}catch{setToast('Could not delete activity. Please try again.')}};
 const saveTarget=async()=>{try{const res=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({weeklyTarget:target})});if(!res.ok)throw new Error();setToast('Weekly target saved.')}catch{setToast('Could not save target.')}};
 const loadDemo=async()=>{try{const saved=await Promise.all(seed().map(e=>fetch('/api/activities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:e.type,quantity:e.quantity,date:e.date,note:e.note})}).then(r=>r.json())));setEntries(saved.map(fromApi));setToast('Demo activities loaded.')}catch{setToast('Could not load demo data.')}};
 const clearAll=async()=>{if(!confirm('Clear all saved activities?'))return;try{const res=await fetch('/api/activities',{method:'DELETE'});if(!res.ok)throw new Error();setEntries([]);setToast('All activities cleared.')}catch{setToast('Could not clear activities.')}};
 const nav=[['Dashboard',BarChart3],['Log activity',Plus],['History',CalendarDays],['Weekly target',Target],['Settings & about',Settings]] as const;
 const filtered=useMemo(()=>entries.filter(e=>filters.type==='All'||e.type===filters.type).filter(e=>filters.range==='All time'||(filters.range==='This week'?inWeek(e.date):filters.range==='This month'?e.date.slice(0,7)===isoToday().slice(0,7):(!filters.from||e.date>=filters.from)&&(!filters.to||e.date<=filters.to))).sort((a,b)=>filters.sort==='Newest'?b.date.localeCompare(a.date):filters.sort==='Oldest'?a.date.localeCompare(b.date):filters.sort==='Highest'?b.co2-a.co2:a.co2-b.co2),[entries,filters]);
 const openLog=()=>{setPage('Log activity');setShowForm(false);setMenu(false)};
 const renderDashboard=<><div className="hero"><div><span className="eyebrow">YOUR CLIMATE SNAPSHOT</span><h1>Small choices. <em>Real impact.</em></h1><p>Track the everyday habits that shape your footprint.</p></div><button className="dark-btn" onClick={()=>setShowForm(true)}><Plus size={18}/> Log an activity</button><div className="hero-orb">🌍</div></div>
 <section className="stats"><Stat icon="◌" name="Total footprint" value={`${fmt(total)} kg`} sub="All recorded activity"/><Stat icon="◷" name="This week" value={`${fmt(weekCO2)} kg`} sub={`${weekly.length} activities logged`}/><Stat icon="◒" name="Weekly target" value={`${fmt(target)} kg`} sub="Your personal goal"/><Stat icon={remaining>=0?'✦':'!'} name={remaining>=0?'Remaining budget':'Over target'} value={`${fmt(Math.abs(remaining))} kg`} sub={remaining>=0?'Keep it going!':'Time for a reset'} warn={remaining<0}/></section>
 <section className={`nudge ${progress>=100?'over':''}`}><div className="nudge-icon">{progress>=100?'🌱':'✦'}</div><div><b>{progress>=100?'Weekly target exceeded — with care.':'You’re within your weekly target.'}</b><p>{progress>=100?`You’ve used ${Math.round(progress)}% of your target. Consider a lower-carbon trip or meal this week.`:`You have ${fmt(remaining)} kg CO₂ left this week. Every mindful choice adds up.`}</p></div><div className="nudge-num"><strong>{Math.round(progress)}%</strong><span>used</span></div></section>
 <div className="grid-two"><section className="panel"><div className="panel-title"><div><span className="eyebrow">WEEKLY RHYTHM</span><h2>This week</h2></div><span className="tiny">Mon — Sun</span></div><div className="chart">{days.map(d=><div className="bar-wrap" key={d.date}><div className="bar-value">{d.value?fmt(d.value):''}</div><div className={`bar ${d.today?'today':''}`} style={{height:`${Math.max(d.value?12:3,Math.min(150,(d.value/(Math.max(...days.map(x=>x.value),1))*145)))}px`}}></div><span>{d.label}</span></div>)}</div><div className="chart-note"><i></i> Today <span>Current weekly footprint: {fmt(weekCO2)} kg CO₂</span></div></section>
 <section className="panel"><div className="panel-title"><div><span className="eyebrow">WHERE IT COMES FROM</span><h2>By category</h2></div><button className="text-btn" onClick={()=>setPage('History')}>See history</button></div>{cats.length?<div className="categories">{cats.map(c=><div className="cat" key={c.type}><span className="emoji">{FACTORS[c.type].icon}</span><div><b>{c.type}</b><small>{fmt(c.value)} kg CO₂</small></div><div className="cat-track"><i style={{width:`${c.value/Math.max(...cats.map(x=>x.value))*100}%`,background:FACTORS[c.type].color}}/></div></div>)}</div>:<Empty text="No emission data available yet."/>}</section></div>
 <section className="panel recent"><div className="panel-title"><div><span className="eyebrow">LATEST ENTRIES</span><h2>Recent activity</h2></div><button className="text-btn" onClick={()=>setPage('History')}>View all</button></div>{entries.length?<EntryList items={entries.slice(0,4)} onDelete={setDel}/>:<Empty text="No activities recorded yet. Start by logging your first activity." action={()=>setShowForm(true)}/>}</section></>;
 const renderLog=<section className="form-page"><span className="eyebrow">MAKE IT COUNT</span><h1>Log an activity</h1><p>Every entry gives you a clearer picture of your impact.</p><ActivityForm form={form} setForm={setForm} add={add} saving={saving}/></section>;
 const renderHistory=<section className="history"><span className="eyebrow">YOUR RECORD</span><h1>Activity history</h1><div className="filters"><label>Activity<select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option>All</option>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><label>Period<select value={filters.range} onChange={e=>setFilters({...filters,range:e.target.value})}><option>All time</option><option>This week</option><option>This month</option><option>Custom range</option></select></label>{filters.range==='Custom range'&&<><label>From<input type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></label><label>To<input type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></label></>}<label>Sort by<select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option>Newest</option><option>Oldest</option><option>Highest</option><option>Lowest</option></select></label></div><section className="panel"><EntryList items={filtered} onDelete={setDel} empty="No activities match your filters."/></section></section>;
 const renderTarget=<section className="form-page"><span className="eyebrow">YOUR NORTH STAR</span><h1>Weekly target</h1><p>Set a realistic target to make steady progress, your way.</p><div className="target-card"><div className="target-symbol"><Target/></div><h2>Weekly CO₂ budget</h2><p>This covers Monday 00:00 through Sunday 23:59 in your local time.</p><div className="target-input"><input type="number" min="0.1" value={target} onChange={e=>setTarget(Math.max(.1,Number(e.target.value)))} /><span>kg CO₂</span></div><button className="dark-btn" onClick={saveTarget}>Save target</button></div></section>;
 const renderSettings=<section className="form-page"><span className="eyebrow">PLANETPULSE</span><h1>Settings & about</h1><div className="about"><Leaf/><h2>Thoughtful tracking for lighter living.</h2><p>PlanetPulse turns daily activity into a clear, kind view of your carbon footprint. Emission factors are fixed according to the hackathon brief.</p><div className="factors">{TYPES.map(t=><div key={t}><span>{FACTORS[t].icon}</span><b>{t}</b><small>{FACTORS[t].factor} kg CO₂ / {FACTORS[t].unit.slice(0,-1)||FACTORS[t].unit}</small></div>)}</div><button className="outline" onClick={loadDemo}>Load demo data</button><button className="danger" onClick={clearAll}>Clear all data</button><p className="version">PlanetPulse v1.0 · Weeks run Monday–Sunday</p></div></section>;
 const content=page==='Dashboard'?renderDashboard:page==='Log activity'?renderLog:page==='History'?renderHistory:page==='Weekly target'?renderTarget:renderSettings;
 return <div className="app"><aside className={menu?'mobile-open':''}><div className="brand"><span><Leaf size={21}/></span>PlanetPulse <button onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([n,I])=><button className={page===n||(n==='Log activity'&&page==='Log activity')?'active':''} key={n} onClick={()=>{n==='Log activity'?openLog():(setPage(n),setMenu(false))}}><I size={18}/>{n}</button>)}</nav><div className="side-bottom"><div className="mini-circle">{Math.min(100,Math.round(progress))}%</div><div><b>This week</b><small>{fmt(weekCO2)} of {fmt(target)} kg</small></div></div></aside><main><header><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu/></button><div className="crumb">{page==='Dashboard'?'Good morning, Earthling':page}</div><div className="date"><CloudSun size={20}/>{new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})}</div></header>{loading?<div className="empty"><Leaf/><p>Loading your climate snapshot…</p></div>:content}</main>{showForm&&<div className="modal-back"><div className="modal"><button className="close" onClick={()=>setShowForm(false)}><X/></button><span className="eyebrow">NEW ACTIVITY</span><h2>What did your day look like?</h2><ActivityForm form={form} setForm={setForm} add={add} saving={saving}/></div></div>}{absurd&&<div className="modal-back"><div className="modal warning"><div className="warning-icon">!</div><h2>That looks unusually high</h2><p><b>{Number(form.quantity).toLocaleString()} {FACTORS[form.type].unit}</b> would generate approximately <b>{fmt(calculate(form.type,Number(form.quantity)).co2)} kg CO₂</b>. Please verify your value before continuing.</p><div className="modal-actions"><button className="outline" onClick={()=>setAbsurd(false)}>Edit value</button><button className="dark-btn" disabled={saving} onClick={()=>add(true)}>{saving?'Saving…':'Continue anyway'}</button></div></div></div>}{del&&<div className="modal-back"><div className="modal confirm"><h2>Delete this activity?</h2><p>This action can’t be undone.</p><div className="modal-actions"><button className="outline" onClick={()=>setDel(null)}>Keep it</button><button className="danger" onClick={()=>remove(del)}>Delete activity</button></div></div></div>}{toast&&<div className="toast">{toast}<button onClick={()=>setToast('')}>×</button></div>}</div>
}
function Stat({icon,name,value,sub,warn}:{icon:string,name:string,value:string,sub:string,warn?:boolean}){return <div className={`stat ${warn?'stat-warn':''}`}><span className="stat-icon">{icon}</span><div><small>{name}</small><strong>{value}</strong><em>{sub}</em></div></div>}
function Empty({text,action}:{text:string,action?:()=>void}){return <div className="empty"><Leaf/><p>{text}</p>{action&&<button className="outline" onClick={action}>Log activity</button>}</div>}
function EntryList({items,onDelete,empty}:{items:Entry[],onDelete:(id:string)=>void,empty?:string}){if(!items.length)return <Empty text={empty||'No activities recorded yet.'}/>;return <div className="entry-list">{items.map(e=><div className="entry" key={e.id}><span className="entry-icon">{FACTORS[e.type].icon}</span><div className="entry-main"><b>{e.type}{e.unusual&&<span className="flag">unusual</span>}</b><small>{new Date(e.date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}{e.note&&` · ${e.note}`}</small></div><div className="entry-qty">{e.quantity} {e.unit}</div><b className="entry-co2">{fmt(e.co2)} <small>kg CO₂</small></b><button className="delete" aria-label={`Delete ${e.type}`} onClick={()=>onDelete(e.id)}><Trash2 size={17}/></button></div>)}</div>}
function ActivityForm({form,setForm,add,saving}:{form:{type:Type;quantity:string;date:string;note:string};setForm:React.Dispatch<React.SetStateAction<{type:Type;quantity:string;date:string;note:string}>>;add:(x?:boolean)=>void;saving:boolean}){const q=Number(form.quantity)||0,c=calculate(form.type,q);return <div className="activity-form"><label>Activity type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value as Type})}>{TYPES.map(x=><option key={x}>{x}</option>)}</select></label><div className="form-row"><label>Quantity<div className="with-unit"><input type="number" min="0" step="any" placeholder="0" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/><span>{c.unit}</span></div></label><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></div><label>Note <span className="optional">optional</span><input placeholder="e.g. commute to work" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><div className="calc"><span>ESTIMATED FOOTPRINT</span><strong>{fmt(c.co2)} kg CO₂</strong><p>{q||0} {c.unit} × {c.factor} kg/{c.unit.slice(0,-1)||c.unit} <b>= {fmt(c.co2)} kg CO₂</b></p></div><button className="dark-btn full" disabled={saving} onClick={()=>add()}>{saving?'Saving…':'Save activity'} <Plus size={17}/></button></div>}
createRoot(document.getElementById('root')!).render(<App/>);
